package ru.temposta.app.service;

public enum Endpoint {
    GET_TASKS,
    GET_TASK_BY_ID,
    POST_TASK,
    DELETE_TASK_BY_ID,
    GET_SUBTASKS,
    GET_SUBTASK_BY_ID,
    POST_SUBTASK,
    DELETE_SUBTASK_BY_ID,
    GET_EPICS,
    GET_EPIC_BY_ID,
    GET_EPIC_SUBTASKS_BY_ID,
    POST_EPIC,
    DELETE_EPIC_BY_ID,
    GET_HISTORY,
    GET_PRIORITIZED_TASKS,
    NONE
}
